import heroImg from "@/assets/hero-1.jpg";
import article1 from "@/assets/article-1.jpg";
import article2 from "@/assets/article-2.jpg";
import article3 from "@/assets/article-3.jpg";
import article4 from "@/assets/article-4.jpg";
import article5 from "@/assets/article-5.jpg";
import article6 from "@/assets/article-6.jpg";
import type { Article } from "./types";

export const articles: Article[] = [
  {
    id: "1",
    title: "Sénégal : La scène artistique de Dakar s'impose sur le marché mondial",
    excerpt: "Une nouvelle génération d'artistes plasticiens transforme le paysage culturel avec des oeuvres innovantes et une présence internationale.",
    category: "Culture",
    image: article1,
    author: "Aminata Diallo",
    date: "11 fév. 2026",
    readTime: "5 min",
    featured: true,
    orientation: "horizontal",
    views: "1.2M",
    duration: "10:15",
    tags: ["Exposition", "Arts plastiques"],
  },
  {
    id: "2",
    title: "Gastronomie : La renaissance des saveurs locales à travers la cuisine fusion",
    excerpt: "Reportage auprès des chefs dakarois qui revisitent les classiques sénégalais.",
    category: "Lifestyle",
    image: article2,
    author: "Moussa Traoré",
    date: "8 févr.",
    readTime: "4 min",
    orientation: "horizontal",
    views: "2.5M",
    duration: "5:30",
    tags: ["Cuisine", "Gastronomie"],
  },
  {
    id: "3",
    title: "Sport urbain : L'ascension fulgurante du basketball de rue à Saint-Louis",
    excerpt: "Comment le basket devient un vecteur d'inclusion sociale pour la jeunesse.",
    category: "Sport",
    image: article3,
    author: "Fatou Sow",
    date: "8 févr.",
    readTime: "2 min",
    orientation: "horizontal",
    views: "950K",
    duration: "2:12",
    tags: ["Basketball", "Jeunesse"],
  },
  {
    id: "4",
    title: "Littérature : Le succès grandissant des nouveaux auteurs sénégalais",
    excerpt: "Portrait d'une génération qui écrit le futur du pays.",
    category: "Culture",
    image: article4,
    author: "Kofi Mensah",
    date: "7 févr.",
    readTime: "3 min",
    orientation: "horizontal",
    views: "780K",
    duration: "3:45",
    tags: ["Livre", "Écriture"],
  },
  {
    id: "5",
    title: "La street fashion sénégalaise explose sur les réseaux",
    excerpt: "Portrait créatif Mode.",
    category: "Tendances",
    image: article5,
    author: "Ousmane Ba",
    date: "11 févr.",
    readTime: "6 min",
    orientation: "horizontal",
    views: "3.5M",
    duration: "3:20",
    tags: ["Portrait créatif", "Mode"],
  },
  {
    id: "6",
    title: "Top 5 des destinations insolites à découvrir en Casamance",
    excerpt: "Un voyage au coeur de la nature sauvage.",
    category: "Tourisme",
    image: article6,
    author: "Awa Ndiaye",
    date: "10 févr.",
    readTime: "5 min",
    orientation: "horizontal",
    views: "4.2M",
    duration: "6:10",
    tags: ["Voyage", "Nature"],
  },
  {
    id: "7",
    title: "Technologie : Les startups de la GreenTech révolutionnent l'agriculture",
    excerpt: "Des solutions locales pour une souveraineté alimentaire durable.",
    category: "Économie",
    image: article1,
    author: "Rédaction Prisme",
    date: "9 févr.",
    readTime: "4 min",
    orientation: "horizontal",
    views: "5.8M",
    duration: "2:45",
    tags: ["Agriculture", "Tech"],
  },
  {
    id: "8",
    title: "Musique : Le retour en force des instruments traditionnels",
    excerpt: "Kora, balafon et sabar s'invitent dans les productions modernes.",
    category: "Culture",
    image: article2,
    author: "Rédaction Prisme",
    date: "8 févr.",
    readTime: "12 min",
    orientation: "horizontal",
    views: "2.9M",
    duration: "13:30",
    tags: ["Musique", "Tradition"],
  },
  {
    id: "9",
    title: "Entrepreneuriat : Le boom du 'Made in Senegal' chez les jeunes créateurs",
    excerpt: "Focus sur ces marques qui misent sur le savoir-faire local.",
    category: "Économie",
    image: article3,
    author: "Rédaction Prisme",
    date: "7 févr.",
    readTime: "8 min",
    orientation: "horizontal",
    views: "1.8M",
    duration: "8:15",
    tags: ["Business", "Local"],
  },
];

export const heroArticle = {
  id: "hero",
  title: "Grand Angle : La transformation numérique des services publics au Sénégal",
  excerpt: "Comment la digitalisation simplifie la vie quotidienne des citoyens.",
  category: "Économie",
  image: "https://res.cloudinary.com/dlna2kuo1/image/upload/v1770895490/JOJ_irk16p.jpg",
  author: "Rédaction Prisme",
  date: "10 févr.",
  readTime: "8 min",
  featured: true,
  orientation: "horizontal",
  views: "1.2M",
  duration: "4:15",
  tags: ["Digital", "Société"],
};
